### ISSUE TITLE
Git merge and rebase error

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/group-project#243]
White boarding our git workflow, and ran into merge conflict when we tried to implement it. Requesting assistance to better understand our problem.

**Comment by MicFin** [comment]
Coming over with @BenGitsCode

**Comment by novakw267** [comment]
Thank you for the assistance, we were able to figure out how resolve the issue and resolve it to a good point.

**Comment by MicFin** [comment]
I think the lessons learned here were really valuable.  Please explain what the issue was and how it was resolved.  Your squad can also add to this issue.

**Comment by novakw267** [comment]
Uh, I honestly wasn't the one with the direct issue. I am not entirely sure how what happened happened. Maybe @wilsonkaya @SquirtleSquad1988 @AshlenPrice can tell you more.

**Comment by AshlenPrice** [comment]
We are still not 100% sure on why we had such nasty merge conflicts with Git. 
We first made development the default branch so that we wouldn't as a group accidentally do any pull request or merge things to master. 
After that, a pair of us branched off development to another branch to work on one of our resources and the other pair did the same for another resource. When each pair finished we were trying to merge into development. One pair was successful at that and the other me and Fatih were not able to complete a rebase because of the conflict in our routes. The conflict was basically on one file in the routes we had a pages resource and the other had a blog resource. Git wanted us to get rid of one when we needed both. So we resolved the merge conflict first and completed the rebase then we added in the additional resource. 

**Learned lessons:**
- Ensure that when working on separate branches that we don't make changes or edits to the same files in our directory. Example if I am making the ajax calls for ```blogs```, and Alex is working on coding the ajax calls for ```pages```, neither one of us should alter any other files, like the ```index.html```.
- Do a better job of communicating when things have been merged to the development branch and ensure that the whole team pulls and rebases their work immediately after. 
- Don't push to your remote branch in the middle of a paused rebase. You need to abort the rebase before pushing anything. 
- Don't change your default branch to anything other than master.

**Comment by BenGitsCode** [comment]
Great insights here team! I really like the format of `learned lessons` here.  You may not always understand the problem you've resolved as completely as you'd like to—but as long as you're learning and growing from them, you're doing it right. 👍
